### ISSUE TITLE
ValueError in case of lists in features dict

### ISSUE THREAD

**Issue by czwartaoslpoj** [COMPREDICT-GmbH/ai-sdk-python#38]
**Describe the bug**
ValueError is raised if user pass features dict with lists inside, like: {'example': [1,2,3,4]}

**To Reproduce**
Call run_algorithm with features as indicated above.

**Expected behavior**
No error is raised.

Since df is further written into parquet file, it is required for features dictionary to have keys assign to lists (not single numeric values that require specified index to be converted into df). 

What needs to be done: 
1. Remove index from _process_data method in client
2. When testing _process_data pass dictionaries of lists

**Comment by uzi0espil** [comment]
closed by #39
